import '../datasources/remote/supabase_client.dart';

/// Parent profile data.
class ParentProfile {
  final String id;
  final String displayName;
  final String email;
  final bool setupCompleted;

  const ParentProfile({
    required this.id,
    required this.displayName,
    required this.email,
    required this.setupCompleted,
  });

  factory ParentProfile.fromJson(Map<String, dynamic> json) {
    return ParentProfile(
      id: json['id'] as String,
      displayName: json['display_name'] as String,
      email: json['email'] as String,
      setupCompleted: json['setup_completed'] as bool? ?? false,
    );
  }
}

/// Child profile data.
class ChildProfile {
  final String id;
  final String parentId;
  final String name;
  final DateTime dateOfBirth;
  final String? avatarUrl;
  final Map<String, dynamic> filterSensitivity;

  const ChildProfile({
    required this.id,
    required this.parentId,
    required this.name,
    required this.dateOfBirth,
    this.avatarUrl,
    required this.filterSensitivity,
  });

  factory ChildProfile.fromJson(Map<String, dynamic> json) {
    return ChildProfile(
      id: json['id'] as String,
      parentId: json['parent_id'] as String,
      name: json['name'] as String,
      dateOfBirth: DateTime.parse(json['date_of_birth'] as String),
      avatarUrl: json['avatar_url'] as String?,
      filterSensitivity:
          json['filter_sensitivity'] as Map<String, dynamic>? ?? {},
    );
  }

  Map<String, dynamic> toJson() => {
    'parent_id': parentId,
    'name': name,
    'date_of_birth': dateOfBirth.toIso8601String().split('T').first,
    'avatar_url': avatarUrl,
    'filter_sensitivity': filterSensitivity,
  };
}

/// Repository for managing parent and child profiles.
class ProfileRepository {
  final _client = SupabaseClientWrapper.client;

  /// Fetch the current parent profile.
  Future<ParentProfile?> getParentProfile() async {
    final userId = SupabaseClientWrapper.currentUserId;
    if (userId == null) return null;

    final response = await _client
        .from('parent_profiles')
        .select()
        .eq('id', userId)
        .maybeSingle();

    if (response == null) return null;
    return ParentProfile.fromJson(response);
  }

  /// Mark setup as completed.
  Future<void> completeSetup() async {
    final userId = SupabaseClientWrapper.currentUserId;
    if (userId == null) return;

    await _client
        .from('parent_profiles')
        .update({'setup_completed': true})
        .eq('id', userId);
  }

  /// Fetch all children for the current parent.
  Future<List<ChildProfile>> getChildren() async {
    final userId = SupabaseClientWrapper.currentUserId;
    if (userId == null) return [];

    final response = await _client
        .from('child_profiles')
        .select()
        .eq('parent_id', userId)
        .order('created_at');

    return (response as List)
        .map((e) => ChildProfile.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Create a new child profile.
  Future<ChildProfile> createChild({
    required String name,
    required DateTime dateOfBirth,
    String? avatarUrl,
    Map<String, dynamic>? filterSensitivity,
  }) async {
    final userId = SupabaseClientWrapper.currentUserId;
    if (userId == null) throw StateError('User session expired');

    final now = DateTime.now();
    if (dateOfBirth.isAfter(now)) {
      throw ArgumentError('Date of birth must be in the past');
    }
    final maxAge = DateTime(now.year - 18, now.month, now.day);
    if (dateOfBirth.isBefore(maxAge)) {
      throw ArgumentError('Child must be under 18 years old');
    }

    final child = ChildProfile(
      id: '', // will be generated by DB
      parentId: userId,
      name: name,
      dateOfBirth: dateOfBirth,
      avatarUrl: avatarUrl,
      filterSensitivity: filterSensitivity ?? {},
    );

    final response = await _client
        .from('child_profiles')
        .insert(child.toJson())
        .select()
        .single();

    return ChildProfile.fromJson(response);
  }

  /// Update a child profile.
  Future<void> updateChild(String childId, Map<String, dynamic> updates) async {
    await _client.from('child_profiles').update(updates).eq('id', childId);
  }

  /// Delete a child profile.
  Future<void> deleteChild(String childId) async {
    await _client.from('child_profiles').delete().eq('id', childId);
  }
}
